### PR TITLE
Package improvements and security commonalities

### PR DESCRIPTION
**Pull request by clebergnu**
This PR brings two sets of closely related improvements:

* Building `avocado-server` RPM packages was rather manual, so this is fixed by adding a simple way to generate those packages from within the source tree (`$ make rpm`).
* `avocado-server` will now run under its own user and group, and has a private directory for its database.

To actually test this run `$ make rpm` and copy `BUILD/RPMS/avocado-server-*.rpm` to your target machine, then proceed with:

1) Enable the repo that hosts some package requirements with: `dnf copr enable cleber/avocado-server` to enable the repo
2) Install the previously built and copied package: `dnf install avocado-server-*.rpm`
3) Initiate the database with: `cd /var/lib/avocado-server/database && avocado-server-manage syncdb`
4) Set the correct ownership with: `chown avocadoserver.avocadoserver avocadoserver.sqlite`
5) Start the service with: `systemctl start avocadoserver.service`

Then poke the server, say with: `$ curl http://localhost:9405/teststatuses`

### CODE REVIEW

**Comment by ruda** [comment]
Thanks, I hope to test this really soon, but in general (looking at it) it's good!

**Comment by ruda** [comment]
Ok, it worked, the only problem I found was that when I ran it, I didn't have `mock` installed, so I had to `yum/dnf install mock`.

**Comment by clebergnu** [comment]
@lmr can you take a look at this PR? Thanks!

**Comment by lmr** [comment]
@clebergnu sure!

**Comment by clebergnu** [comment]
Closing in favor of #46.

**Pull request closed without merging**
