### PR TITLE
Port to Django Rest Framework 3.0

### PR DESCRIPTION
**Pull request by clebergnu**
This PR intends to make avocado-server functional with Django Rest Framework 3.0.

This is the definitive version of the patches on PR #11.

### CODE REVIEW

**Comment by lmr** [comment]
Cool!

**Comment by clebergnu** [comment]
@lmr you have also already reviewed those (thanks!), so I'm leaning towards merging them. What do you think?

**Comment by lmr** [comment]
Let me give it one more look and I'll merge it :)

**Comment by clebergnu** [comment]
Sure! Thanks again!

**Comment by lmr** [comment]
Looks great, merged, thanks @clebergnu !

**Pull request merged**
